services:
  redis:
    image: redis
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - ewallet-network

  ewallet:
    build: .
    container_name: ewallet
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - ewallet-network

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    command:
      - "--collector.otlp.enabled=true"
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "14268:14268" # Jaeger HTTP Thrift (optional)
    environment:
      - LOG_LEVEL=debug
    networks:
      - ewallet-network

volumes:
  postgres-data:
    driver: local

networks:
  ewallet-network:
    driver: bridge
    external: true
