services:
  
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    command:
      - "--collector.otlp.enabled=true"
    ports:
      - "16686:16686"      # Jaeger UI
      - "4317:4317"        # OTLP gRPC
      - "4318:4318"        # OTLP HTTP
      - "14268:14268"      # Jaeger HTTP Thrift (optional)
    environment:
      - LOG_LEVEL=debug

volumes:
  kafka-data:

networks:
  default:
    driver: bridge
